// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;


public class HexBase : object {
    
    private Int32 _XIndex;
    
    private Int32 _YIndex;
    
    private Vector3 _CubeIndex;
    
    private Int32 _Elevation;
    
    private Int32 _Humidity;
    
    private Int32 _Temperature;
    
    private Vector3 _WorldPos;
    
    private TerrainType _TerrainType;
    
    private VegetationState _VegetationState;
    
    private System.Collections.Generic.List<ResourceViewModel> _Resources;
    
    public Int32 XIndex {
        get {
            return _XIndex;
        }
        set {
            _XIndex = value;
        }
    }
    
    public Int32 YIndex {
        get {
            return _YIndex;
        }
        set {
            _YIndex = value;
        }
    }
    
    public Vector3 CubeIndex {
        get {
            return _CubeIndex;
        }
        set {
            _CubeIndex = value;
        }
    }
    
    public Int32 Elevation {
        get {
            return _Elevation;
        }
        set {
            _Elevation = value;
        }
    }
    
    public Int32 Humidity {
        get {
            return _Humidity;
        }
        set {
            _Humidity = value;
        }
    }
    
    public Int32 Temperature {
        get {
            return _Temperature;
        }
        set {
            _Temperature = value;
        }
    }
    
    public Vector3 WorldPos {
        get {
            return _WorldPos;
        }
        set {
            _WorldPos = value;
        }
    }
    
    public TerrainType TerrainType {
        get {
            return _TerrainType;
        }
        set {
            _TerrainType = value;
        }
    }
    
    public VegetationState VegetationState {
        get {
            return _VegetationState;
        }
        set {
            _VegetationState = value;
        }
    }
    
    public System.Collections.Generic.List<ResourceViewModel> Resources {
        get {
            return _Resources;
        }
        set {
            _Resources = value;
        }
    }
}
