// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;


public partial class GenerateTerrainCommand : ViewModelCommand {
}

public partial class GenerateChunksCommand : ViewModelCommand {
}

public partial class ErosionCommand : ViewModelCommand {
}

public partial class GenerateChunkCommand : ViewModelCommand {
}

public partial class GenerateWorldCommand : ViewModelCommand {
}
