// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;
using uFrame.Serialization;


public class TestingSceneBase : uFrame.Kernel.Scene {
    
    public override string DefaultKernelScene {
        get {
            return "GrandStrategyKernelScene";
        }
    }
    
    public virtual TestingSceneSettings Settings {
        get {
            return _SettingsObject as TestingSceneSettings;
        }
        set {
            _SettingsObject = value;
        }
    }
}

public class TestingSceneLoaderBase : SceneLoader<TestingScene> {
    
    protected override IEnumerator LoadScene(TestingScene scene, Action<float, string> progressDelegate) {
        yield break;
    }
    
    protected override IEnumerator UnloadScene(TestingScene scene, Action<float, string> progressDelegate) {
        yield break;
    }
}
