// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UniRx;
using UnityEngine;


public class TerrainPreviewViewBase : ViewBase {
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _Width;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _Height;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _Elevations;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _SeaLevel;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _Seed;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Boolean _RandomizedSeed;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _DiamonDetail;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _DiamondVariation;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RiverFrequency;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RiverLength;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _MountainRangeFrequency;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _MountainRangeScale;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _MountainSpacing;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public ChunkViewModel[,] _Chunks;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Hex[,] _Hexes;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _ChunkSize;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _HexSideLength;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _PixelsPerUnit;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single[,] _TerrainHeights;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _PixelsToHeight;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _ErrosionPasses;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single[,] _Rainfall;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RainfallMovementSteps;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RainfallNeighbors;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _RiverMinHeight;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RiverMinLength;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RiverMaxLength;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _LakeMinSize;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _SeaMinSize;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _ChunkHexCountX;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _ChunkHexCountY;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Vector3 _CameraPos;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public AnimationCurve _LatitudeTempCurve;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public TerrainTypesList _TerrainTypesList;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public AnimationCurve _AltitudeTempCurve;
    
    [UFToggleGroup("GenerateChunks")]
    [UnityEngine.HideInInspector()]
    public bool _BindGenerateChunks = true;
    
    public override string DefaultIdentifier {
        get {
            return "Terrain";
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(TerrainViewModel);
        }
    }
    
    public TerrainViewModel Terrain {
        get {
            return (TerrainViewModel)ViewModelObject;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel();
    }
    
    protected override void InitializeViewModel(ViewModel model) {
        base.InitializeViewModel(model);
        var terrainpreviewview = ((TerrainViewModel)model);
        terrainpreviewview.Width = this._Width;
        terrainpreviewview.Height = this._Height;
        terrainpreviewview.Elevations = this._Elevations;
        terrainpreviewview.SeaLevel = this._SeaLevel;
        terrainpreviewview.Seed = this._Seed;
        terrainpreviewview.RandomizedSeed = this._RandomizedSeed;
        terrainpreviewview.DiamonDetail = this._DiamonDetail;
        terrainpreviewview.DiamondVariation = this._DiamondVariation;
        terrainpreviewview.RiverFrequency = this._RiverFrequency;
        terrainpreviewview.RiverLength = this._RiverLength;
        terrainpreviewview.MountainRangeFrequency = this._MountainRangeFrequency;
        terrainpreviewview.MountainRangeScale = this._MountainRangeScale;
        terrainpreviewview.MountainSpacing = this._MountainSpacing;
        terrainpreviewview.Chunks = this._Chunks;
        terrainpreviewview.Hexes = this._Hexes;
        terrainpreviewview.ChunkSize = this._ChunkSize;
        terrainpreviewview.HexSideLength = this._HexSideLength;
        terrainpreviewview.PixelsPerUnit = this._PixelsPerUnit;
        terrainpreviewview.TerrainHeights = this._TerrainHeights;
        terrainpreviewview.PixelsToHeight = this._PixelsToHeight;
        terrainpreviewview.ErrosionPasses = this._ErrosionPasses;
        terrainpreviewview.Rainfall = this._Rainfall;
        terrainpreviewview.RainfallMovementSteps = this._RainfallMovementSteps;
        terrainpreviewview.RainfallNeighbors = this._RainfallNeighbors;
        terrainpreviewview.RiverMinHeight = this._RiverMinHeight;
        terrainpreviewview.RiverMinLength = this._RiverMinLength;
        terrainpreviewview.RiverMaxLength = this._RiverMaxLength;
        terrainpreviewview.LakeMinSize = this._LakeMinSize;
        terrainpreviewview.SeaMinSize = this._SeaMinSize;
        terrainpreviewview.ChunkHexCountX = this._ChunkHexCountX;
        terrainpreviewview.ChunkHexCountY = this._ChunkHexCountY;
        terrainpreviewview.CameraPos = this._CameraPos;
        terrainpreviewview.LatitudeTempCurve = this._LatitudeTempCurve;
        terrainpreviewview.TerrainTypesList = this._TerrainTypesList;
        terrainpreviewview.AltitudeTempCurve = this._AltitudeTempCurve;
    }
    
    public override void Bind() {
        base.Bind();
        if (_BindGenerateChunks) {
            this.BindCommandExecuted(this.Terrain.GenerateChunks, this.GenerateChunksExecuted);
        }
    }
    
    public virtual void GenerateChunksExecuted(GenerateChunksCommand command) {
    }
    
    public virtual void ExecuteGenerateTerrain() {
        Terrain.GenerateTerrain.OnNext(new GenerateTerrainCommand() { Sender = Terrain });
    }
    
    public virtual void ExecuteGenerateChunks() {
        Terrain.GenerateChunks.OnNext(new GenerateChunksCommand() { Sender = Terrain });
    }
    
    public virtual void ExecuteErosion() {
        Terrain.Erosion.OnNext(new ErosionCommand() { Sender = Terrain });
    }
    
    public virtual void ExecuteGenerateTerrain(GenerateTerrainCommand command) {
        command.Sender = Terrain;
        Terrain.GenerateTerrain.OnNext(command);
    }
    
    public virtual void ExecuteGenerateChunks(GenerateChunksCommand command) {
        command.Sender = Terrain;
        Terrain.GenerateChunks.OnNext(command);
    }
    
    public virtual void ExecuteErosion(ErosionCommand command) {
        command.Sender = Terrain;
        Terrain.Erosion.OnNext(command);
    }
}

public class ChunkViewBase : ViewBase {
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _XIndex;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _YIndex;
    
    public override string DefaultIdentifier {
        get {
            return base.DefaultIdentifier;
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(ChunkViewModel);
        }
    }
    
    public ChunkViewModel Chunk {
        get {
            return (ChunkViewModel)ViewModelObject;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel();
    }
    
    protected override void InitializeViewModel(ViewModel model) {
        base.InitializeViewModel(model);
        var chunkview = ((ChunkViewModel)model);
        chunkview.XIndex = this._XIndex;
        chunkview.YIndex = this._YIndex;
    }
    
    public override void Bind() {
        base.Bind();
    }
    
    public virtual void ExecuteGenerateChunk() {
        Chunk.GenerateChunk.OnNext(new GenerateChunkCommand() { Sender = Chunk });
    }
    
    public virtual void ExecuteGenerateChunk(GenerateChunkCommand command) {
        command.Sender = Chunk;
        Chunk.GenerateChunk.OnNext(command);
    }
}

public class TerrainViewBase : ViewBase {
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _Width;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _Height;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _Elevations;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _SeaLevel;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _Seed;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Boolean _RandomizedSeed;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _DiamonDetail;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _DiamondVariation;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RiverFrequency;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RiverLength;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _MountainRangeFrequency;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _MountainRangeScale;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _MountainSpacing;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public ChunkViewModel[,] _Chunks;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Hex[,] _Hexes;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _ChunkSize;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _HexSideLength;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _PixelsPerUnit;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single[,] _TerrainHeights;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _PixelsToHeight;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _ErrosionPasses;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single[,] _Rainfall;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RainfallMovementSteps;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RainfallNeighbors;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _RiverMinHeight;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RiverMinLength;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RiverMaxLength;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _LakeMinSize;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _SeaMinSize;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _ChunkHexCountX;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _ChunkHexCountY;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Vector3 _CameraPos;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public AnimationCurve _LatitudeTempCurve;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public TerrainTypesList _TerrainTypesList;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public AnimationCurve _AltitudeTempCurve;
    
    public override string DefaultIdentifier {
        get {
            return "Terrain";
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(TerrainViewModel);
        }
    }
    
    public TerrainViewModel Terrain {
        get {
            return (TerrainViewModel)ViewModelObject;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel();
    }
    
    protected override void InitializeViewModel(ViewModel model) {
        base.InitializeViewModel(model);
        var terrainview = ((TerrainViewModel)model);
        terrainview.Width = this._Width;
        terrainview.Height = this._Height;
        terrainview.Elevations = this._Elevations;
        terrainview.SeaLevel = this._SeaLevel;
        terrainview.Seed = this._Seed;
        terrainview.RandomizedSeed = this._RandomizedSeed;
        terrainview.DiamonDetail = this._DiamonDetail;
        terrainview.DiamondVariation = this._DiamondVariation;
        terrainview.RiverFrequency = this._RiverFrequency;
        terrainview.RiverLength = this._RiverLength;
        terrainview.MountainRangeFrequency = this._MountainRangeFrequency;
        terrainview.MountainRangeScale = this._MountainRangeScale;
        terrainview.MountainSpacing = this._MountainSpacing;
        terrainview.Chunks = this._Chunks;
        terrainview.Hexes = this._Hexes;
        terrainview.ChunkSize = this._ChunkSize;
        terrainview.HexSideLength = this._HexSideLength;
        terrainview.PixelsPerUnit = this._PixelsPerUnit;
        terrainview.TerrainHeights = this._TerrainHeights;
        terrainview.PixelsToHeight = this._PixelsToHeight;
        terrainview.ErrosionPasses = this._ErrosionPasses;
        terrainview.Rainfall = this._Rainfall;
        terrainview.RainfallMovementSteps = this._RainfallMovementSteps;
        terrainview.RainfallNeighbors = this._RainfallNeighbors;
        terrainview.RiverMinHeight = this._RiverMinHeight;
        terrainview.RiverMinLength = this._RiverMinLength;
        terrainview.RiverMaxLength = this._RiverMaxLength;
        terrainview.LakeMinSize = this._LakeMinSize;
        terrainview.SeaMinSize = this._SeaMinSize;
        terrainview.ChunkHexCountX = this._ChunkHexCountX;
        terrainview.ChunkHexCountY = this._ChunkHexCountY;
        terrainview.CameraPos = this._CameraPos;
        terrainview.LatitudeTempCurve = this._LatitudeTempCurve;
        terrainview.TerrainTypesList = this._TerrainTypesList;
        terrainview.AltitudeTempCurve = this._AltitudeTempCurve;
    }
    
    public override void Bind() {
        base.Bind();
    }
    
    public virtual void ExecuteGenerateTerrain() {
        Terrain.GenerateTerrain.OnNext(new GenerateTerrainCommand() { Sender = Terrain });
    }
    
    public virtual void ExecuteGenerateChunks() {
        Terrain.GenerateChunks.OnNext(new GenerateChunksCommand() { Sender = Terrain });
    }
    
    public virtual void ExecuteErosion() {
        Terrain.Erosion.OnNext(new ErosionCommand() { Sender = Terrain });
    }
    
    public virtual void ExecuteGenerateTerrain(GenerateTerrainCommand command) {
        command.Sender = Terrain;
        Terrain.GenerateTerrain.OnNext(command);
    }
    
    public virtual void ExecuteGenerateChunks(GenerateChunksCommand command) {
        command.Sender = Terrain;
        Terrain.GenerateChunks.OnNext(command);
    }
    
    public virtual void ExecuteErosion(ErosionCommand command) {
        command.Sender = Terrain;
        Terrain.Erosion.OnNext(command);
    }
}

public class ChunkManagerViewBase : ViewBase {
    
    private System.IDisposable _CameraPosDisposable;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _Width;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _Height;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _Elevations;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _SeaLevel;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _Seed;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Boolean _RandomizedSeed;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _DiamonDetail;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _DiamondVariation;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RiverFrequency;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RiverLength;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _MountainRangeFrequency;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _MountainRangeScale;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _MountainSpacing;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public ChunkViewModel[,] _Chunks;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Hex[,] _Hexes;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _ChunkSize;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _HexSideLength;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _PixelsPerUnit;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single[,] _TerrainHeights;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _PixelsToHeight;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _ErrosionPasses;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single[,] _Rainfall;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RainfallMovementSteps;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RainfallNeighbors;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _RiverMinHeight;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RiverMinLength;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _RiverMaxLength;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _LakeMinSize;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _SeaMinSize;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _ChunkHexCountX;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _ChunkHexCountY;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Vector3 _CameraPos;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public AnimationCurve _LatitudeTempCurve;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public TerrainTypesList _TerrainTypesList;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public AnimationCurve _AltitudeTempCurve;
    
    [UFToggleGroup("GenerateChunks")]
    [UnityEngine.HideInInspector()]
    public bool _BindGenerateChunks = true;
    
    public override string DefaultIdentifier {
        get {
            return "Terrain";
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(TerrainViewModel);
        }
    }
    
    public TerrainViewModel Terrain {
        get {
            return (TerrainViewModel)ViewModelObject;
        }
    }
    
    public virtual void ResetCameraPos() {
        if (_CameraPosDisposable != null) {
            _CameraPosDisposable.Dispose();
        }
        _CameraPosDisposable = GetCameraPosObservable().Subscribe(Terrain.CameraPosProperty).DisposeWith(this);
    }
    
    protected virtual Vector3 CalculateCameraPos() {
        return default(Vector3);
    }
    
    protected virtual UniRx.IObservable<Vector3> GetCameraPosObservable() {
        return this.UpdateAsObservable().Select(p=>CalculateCameraPos());
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel();
    }
    
    protected override void InitializeViewModel(ViewModel model) {
        base.InitializeViewModel(model);
        var chunkmanagerview = ((TerrainViewModel)model);
        chunkmanagerview.Width = this._Width;
        chunkmanagerview.Height = this._Height;
        chunkmanagerview.Elevations = this._Elevations;
        chunkmanagerview.SeaLevel = this._SeaLevel;
        chunkmanagerview.Seed = this._Seed;
        chunkmanagerview.RandomizedSeed = this._RandomizedSeed;
        chunkmanagerview.DiamonDetail = this._DiamonDetail;
        chunkmanagerview.DiamondVariation = this._DiamondVariation;
        chunkmanagerview.RiverFrequency = this._RiverFrequency;
        chunkmanagerview.RiverLength = this._RiverLength;
        chunkmanagerview.MountainRangeFrequency = this._MountainRangeFrequency;
        chunkmanagerview.MountainRangeScale = this._MountainRangeScale;
        chunkmanagerview.MountainSpacing = this._MountainSpacing;
        chunkmanagerview.Chunks = this._Chunks;
        chunkmanagerview.Hexes = this._Hexes;
        chunkmanagerview.ChunkSize = this._ChunkSize;
        chunkmanagerview.HexSideLength = this._HexSideLength;
        chunkmanagerview.PixelsPerUnit = this._PixelsPerUnit;
        chunkmanagerview.TerrainHeights = this._TerrainHeights;
        chunkmanagerview.PixelsToHeight = this._PixelsToHeight;
        chunkmanagerview.ErrosionPasses = this._ErrosionPasses;
        chunkmanagerview.Rainfall = this._Rainfall;
        chunkmanagerview.RainfallMovementSteps = this._RainfallMovementSteps;
        chunkmanagerview.RainfallNeighbors = this._RainfallNeighbors;
        chunkmanagerview.RiverMinHeight = this._RiverMinHeight;
        chunkmanagerview.RiverMinLength = this._RiverMinLength;
        chunkmanagerview.RiverMaxLength = this._RiverMaxLength;
        chunkmanagerview.LakeMinSize = this._LakeMinSize;
        chunkmanagerview.SeaMinSize = this._SeaMinSize;
        chunkmanagerview.ChunkHexCountX = this._ChunkHexCountX;
        chunkmanagerview.ChunkHexCountY = this._ChunkHexCountY;
        chunkmanagerview.CameraPos = this._CameraPos;
        chunkmanagerview.LatitudeTempCurve = this._LatitudeTempCurve;
        chunkmanagerview.TerrainTypesList = this._TerrainTypesList;
        chunkmanagerview.AltitudeTempCurve = this._AltitudeTempCurve;
    }
    
    public override void Bind() {
        base.Bind();
        if (_BindGenerateChunks) {
            this.BindCommandExecuted(this.Terrain.GenerateChunks, this.GenerateChunksExecuted);
        }
        ResetCameraPos();
    }
    
    public virtual void GenerateChunksExecuted(GenerateChunksCommand command) {
    }
    
    public virtual void ExecuteGenerateTerrain() {
        Terrain.GenerateTerrain.OnNext(new GenerateTerrainCommand() { Sender = Terrain });
    }
    
    public virtual void ExecuteGenerateChunks() {
        Terrain.GenerateChunks.OnNext(new GenerateChunksCommand() { Sender = Terrain });
    }
    
    public virtual void ExecuteErosion() {
        Terrain.Erosion.OnNext(new ErosionCommand() { Sender = Terrain });
    }
    
    public virtual void ExecuteGenerateTerrain(GenerateTerrainCommand command) {
        command.Sender = Terrain;
        Terrain.GenerateTerrain.OnNext(command);
    }
    
    public virtual void ExecuteGenerateChunks(GenerateChunksCommand command) {
        command.Sender = Terrain;
        Terrain.GenerateChunks.OnNext(command);
    }
    
    public virtual void ExecuteErosion(ErosionCommand command) {
        command.Sender = Terrain;
        Terrain.Erosion.OnNext(command);
    }
}

public class PlayerUIBase : ViewBase {
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Hex _SelectedHex;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public ViewBase _Terrain;
    
    [UFToggleGroup("SelectedHex")]
    [UnityEngine.HideInInspector()]
    public bool _BindSelectedHex = true;
    
    [UFGroup("SelectedHex")]
    [UnityEngine.SerializeField()]
    [UnityEngine.Serialization.FormerlySerializedAsAttribute("_SelectedHexonlyWhenChanged")]
    private bool _SelectedHexOnlyWhenChanged;
    
    public override string DefaultIdentifier {
        get {
            return base.DefaultIdentifier;
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(PlayerViewModel);
        }
    }
    
    public PlayerViewModel Player {
        get {
            return (PlayerViewModel)ViewModelObject;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel();
    }
    
    protected override void InitializeViewModel(ViewModel model) {
        base.InitializeViewModel(model);
        var playerui = ((PlayerViewModel)model);
        playerui.SelectedHex = this._SelectedHex;
        playerui.Terrain = this._Terrain == null ? null : this._Terrain.ViewModelObject as TerrainViewModel;
    }
    
    public override void Bind() {
        base.Bind();
        if (_BindSelectedHex) {
            this.BindProperty(this.Player.SelectedHexProperty, this.SelectedHexChanged, _SelectedHexOnlyWhenChanged);
        }
    }
    
    public virtual void SelectedHexChanged(Hex arg1) {
    }
}

public class PlayerViewBase : ViewBase {
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Hex _SelectedHex;
    
    [UnityEngine.SerializeField()]
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public ViewBase _Terrain;
    
    public override string DefaultIdentifier {
        get {
            return base.DefaultIdentifier;
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(PlayerViewModel);
        }
    }
    
    public PlayerViewModel Player {
        get {
            return (PlayerViewModel)ViewModelObject;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel();
    }
    
    protected override void InitializeViewModel(ViewModel model) {
        base.InitializeViewModel(model);
        var playerview = ((PlayerViewModel)model);
        playerview.SelectedHex = this._SelectedHex;
        playerview.Terrain = this._Terrain == null ? null : this._Terrain.ViewModelObject as TerrainViewModel;
    }
    
    public override void Bind() {
        base.Bind();
    }
}
