// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.Serialization;
    using UnityEngine;
    
    
    public class ChunkTreesManagerViewBase : uFrame.MVVM.ViewComponent {
        
        public virtual TerrainViewModel Terrain {
            get {
                return (TerrainViewModel)this.View.ViewModelObject;
            }
        }
        
        public virtual void ExecuteGenerateTerrain() {
            Terrain.GenerateTerrain.OnNext(new GenerateTerrainCommand() { Sender = Terrain });
        }
        
        public virtual void ExecuteErosion() {
            Terrain.Erosion.OnNext(new ErosionCommand() { Sender = Terrain });
        }
        
        public virtual void ExecuteGenerateTerrain(GenerateTerrainCommand command) {
            command.Sender = Terrain;
            Terrain.GenerateTerrain.OnNext(command);
        }
        
        public virtual void ExecuteGenerateChunks(GenerateChunksCommand command) {
            command.Sender = Terrain;
            Terrain.GenerateChunks.OnNext(command);
        }
        
        public virtual void ExecuteErosion(ErosionCommand command) {
            command.Sender = Terrain;
            Terrain.Erosion.OnNext(command);
        }
    }
    
    public class ChunksFogOfWarViewBase : uFrame.MVVM.ViewComponent {
        
        public virtual TerrainViewModel Terrain {
            get {
                return (TerrainViewModel)this.View.ViewModelObject;
            }
        }
        
        public virtual void ExecuteGenerateTerrain() {
            Terrain.GenerateTerrain.OnNext(new GenerateTerrainCommand() { Sender = Terrain });
        }
        
        public virtual void ExecuteErosion() {
            Terrain.Erosion.OnNext(new ErosionCommand() { Sender = Terrain });
        }
        
        public virtual void ExecuteGenerateTerrain(GenerateTerrainCommand command) {
            command.Sender = Terrain;
            Terrain.GenerateTerrain.OnNext(command);
        }
        
        public virtual void ExecuteGenerateChunks(GenerateChunksCommand command) {
            command.Sender = Terrain;
            Terrain.GenerateChunks.OnNext(command);
        }
        
        public virtual void ExecuteErosion(ErosionCommand command) {
            command.Sender = Terrain;
            Terrain.Erosion.OnNext(command);
        }
    }
